### ISSUE TITLE
RunAsUser ?

### ISSUE THREAD

**Issue by c-michail** [D3lphi3r/RunAsSystem#1]
Hello,
  Can you modify to run as user bypassing UAC through the service ? (like domain admin)
  eg, supply: username, password and domain (if available)

Thank you

**Comment by D3lphi3r** [comment]
This is not an issue related to this project, You should consider asking such questions at services like [SO](https://stackoverflow.com)  

Take a look at these APIs [LogonUser](https://msdn.microsoft.com/en-us/library/windows/desktop/aa378184(v=vs.85).aspx) and [CreateProcessWithLogonW](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682431(v=vs.85).aspx) its what you are looking for.

e.g:

```
function RunAsUser(const lpDomain, lpUsername, lpPassword:string; AppPath: string; lpCurrentDirectory: string = 'C:\'):Boolean;
var
  hToken: THANDLE;
  lpvEnv: LPVOID;
  SI: TStartupInfoW;
  PI: TProcessInformation;
begin
  Result := False;
  ZeroMemory(@pi, SizeOf(pi));
  ZeroMemory(@si, SizeOf(si));
  si.cb := SizeOf(TStartupInfo);

  if (LogonUser(pChar(lpUsername), pChar(lpDomain), pChar(lpPassword), LOGON_TYPE_NEW_CREDENTIALS,
          LOGON32_PROVIDER_WINNT50, hToken)) then
  begin
    if (CreateEnvironmentBlock(lpvEnv, hToken, True)) then
    begin
      if (CreateProcessWithLogonW(pChar(lpUsername), pChar(lpDomain), pChar(lpPassword),
              0, nil, pChar(AppPath),
              CREATE_UNICODE_ENVIRONMENT, lpvEnv, pChar(lpCurrentDirectory),
              si, pi)) then
      begin
        Result := True;
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
      end;
      DestroyEnvironmentBlock(lpvEnv);
    end;
    CloseHandle(hToken);
  end;
end;
```

Pass **nil**  (empty string) to the **lpDomain** parameter if you need to create the new process with a local account.

**Comment by c-michail** [comment]
Hello,
  I was talking about launching a process interactive as a User not as a SYSTEM. (which already your project does it beautifully)
  The above code does not work, anyhow i didn't found a solution on SO either.
  I can get eg, to run "cmd.exe" as SYSTEM using the project's code but not as a User.

As far i know neither LogonUser and CreateProcessWithLogonW works from a service :(

Thank you
